# Generated by Django 5.1.4 on 2024-12-13 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-pk']},
        ),
    ]
