# Generated by Django 5.1 on 2024-09-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, upload_to='events_thumbnail')),
                ('date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
