# Generated by Django 5.1 on 2024-08-21 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_forumthread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='forum',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='forumthread',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
        migrations.DeleteModel(
            name='ForumPost',
        ),
        migrations.DeleteModel(
            name='ForumThread',
        ),
    ]
